// <auto-generated />
using System;
using Libreria.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Libreria.Infrastructure.Migrations
{
    [DbContext(typeof(LibreriaDbContext))]
    [Migration("20221004120802_TablesWithData")]
    partial class TablesWithData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Libreria.Domain.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Biografia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Autor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biografia = "es uno de los autores más influyentes de la historia. Su obra, publicada a inicios del siglo XX tardó unos años en encontrar aceptación entre un público más amplio. Entre 1929 y 1936, lanzó cuatro novelas: “El sonido y la furia”, “Mientras agonizo”, “Luz de agosto” y “¡Absalom, Absalom!” que definirían su estilo, inmerso en la exploración de la moralidad dentro del gótico sureño. Sus obras le valieron el Premio Nobel de Literatura en 1949, lo que le dio un nuevo vuelco a su fama.",
                            Nacionalidad = "AMERICANO",
                            Nombre = "WILLIAM FAULKNER"
                        },
                        new
                        {
                            Id = 2,
                            Biografia = "fue un escritor y poeta irlandés cuyo nombre real era Oscar Fingal O'Flahertie Wills Wilde. Nació el 16 de octubre de 1854 en Dublín (Irlanda) y, a principios de la década de 1890, se convirtió en el dramaturgo más famoso de todo Londres. Fue encarcelado, lo que más tarde condujo a su fallecimiento temprano. Hoy es recordado por obras tan notables como “La importancia de llamarse Ernesto”, “El retrato de Dorian Gray”, “El fantasma de Canterville” o “De profundis”",
                            Nacionalidad = "IRLANDES",
                            Nombre = "OSCAR WILDE"
                        },
                        new
                        {
                            Id = 3,
                            Biografia = "En estos días, cada vez que una historia toma un giro surrealista u horrible que pone de relieve la complejidad invencible de un sistema sin rostro, lo llamamos \"kafkiano\". “El proceso” es una novela desgarradora sobre un hombre perseguido por una autoridad omnisciente por un crimen cuya naturaleza nunca se revela. “La Metamorfosis” es un libro igualmente perturbador en el que el narrador se despierta viendo que se ha convertido en un insecto gigante. Las historias de Franz Kafka sondean las áreas más oscuras y menos transitadas de la condición humana, y aunque solo tenía 40 años cuando murió en 1924 (se murió de hambre cuando la tuberculosis hizo que comer fuera demasiado doloroso), sus obras le valieron la reputación de ser uno de los escritores más fabulosos del siglo XX.",
                            Nacionalidad = "AMERICANO",
                            Nombre = "FRANZ KAFKA"
                        },
                        new
                        {
                            Id = 4,
                            Biografia = "nació el 2 de febrero de 1882 y es considerado uno de los autores más influyentes de la historia de la literatura. Sus obras más conocidas son: “Ulises”, “Dublineses”, “Los muertos” o “Eveline”. Una increíble estatua en su honor se encuentra en North Earl Street en Dublín ",
                            Nacionalidad = "ESPAÑOLA",
                            Nombre = "FALCONES, ILDEFONSO"
                        },
                        new
                        {
                            Id = 5,
                            Biografia = "Luis García Montero ​ es un poeta y crítico literario español, ensayista, catedrático de Literatura Española en la Universidad de Granada. Pertenece a la generación de los ochenta o postnovísimos dentro de la corriente denominada poesía de la experiencia. Desde 2018 es Director del Instituto Cervantes.",
                            Nacionalidad = "ESPAÑOLA",
                            Nombre = "GARCÍA MONTERO, LUIS"
                        },
                        new
                        {
                            Id = 6,
                            Biografia = "Joël Dicker es un escritor suizo nacido el 16 de junio del año 1985 en la ciudad de Ginebra.\r\n\r\nEs hijo de un profesor de instituto y de una librera. Tiene tres hermanos.\r\n\r\nSu primer acercamiento a la escritura se produjo en su infancia, cuando en el colegio dirigió una revista de naturaleza y animales.\r\n\r\nEn principio, Joel quería dedicarse a la interpretación, y para ello acudió a París a estudiar arte dramático.",
                            Nacionalidad = "SUIZO",
                            Nombre = "DICKER, JOËL"
                        },
                        new
                        {
                            Id = 7,
                            Biografia = "Stephen Edwin King, más conocido como Stephen King y ocasionalmente por su pseudónimo Richard Bachman, es un escritor estadounidense de novelas de terror, ficción sobrenatural, misterio, ciencia ficción y literatura fantástica",
                            Nacionalidad = "AMERICANO",
                            Nombre = "KING, STEPHEN"
                        },
                        new
                        {
                            Id = 8,
                            Biografia = "Es un mangaka japonés.Matsumoto nació en la región de Kinki, en la prefectura de Hyogo. Estudió en el Asagaya Art College.\r\n\r\nEn 2005, ganó el 27º premio Jump Top 10 Rookie Manga, lo que le permitió empezar a publicar su primer manga, Nekoromancer.",
                            Nacionalidad = "JAPONES",
                            Nombre = "MATSUMOTO, NAOYA"
                        },
                        new
                        {
                            Id = 9,
                            Biografia = "Taylor Jenkins Reid es una escritora, productora de televisión y guionista estadounidense. Escribe principalmente romance y sus obras más destacadas son Los siete maridos de Evelyn Hugo y Todos quieren a Daisy Jones.",
                            Nacionalidad = "INGLES",
                            Nombre = "JENKINS REID, TAYLOR"
                        },
                        new
                        {
                            Id = 10,
                            Biografia = "El conferencista James Clear es un escritor bestseller centrado en los hábitos, la toma de decisiones y la mejora continua. Es el autor del éxito de ventas número 1 del New York Times, Hábitos Atómicos (Atomic Habits). El libro se ha traducido a más de 50 idiomas y ha vendido más de 5 millones de copias.",
                            Nacionalidad = "INGLES",
                            Nombre = "CLEAR, JAMES"
                        });
                });

            modelBuilder.Entity("Libreria.Domain.Editorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Editorial");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "La vaca"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Panfleto"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Editorial Anagrama"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Nube de Tinta"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Espasa"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Tusquets Editores"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Grijalbo"
                        });
                });

            modelBuilder.Entity("Libreria.Domain.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genero");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Ficcion Moderna"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Biografia"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Crimen y misterio"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Motivación personal"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Realismo mágico"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Misterio"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Ficción clásica"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Fantasía"
                        });
                });

            modelBuilder.Entity("Libreria.Domain.Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Asin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EditorialId")
                        .HasColumnType("int");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Paginas")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EditorialId");

                    b.ToTable("Libro");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Asin = "978-84-1107-160-4",
                            EditorialId = 1,
                            Paginas = 180,
                            Titulo = "Esclava de la libertad"
                        },
                        new
                        {
                            Id = 2,
                            Asin = "978-84-253-6179-1",
                            EditorialId = 1,
                            Paginas = 148,
                            Titulo = "Un año y tres meses"
                        },
                        new
                        {
                            Id = 3,
                            Asin = "978-84-339-9954-2",
                            EditorialId = 2,
                            Paginas = 520,
                            Titulo = "Personas decentes"
                        },
                        new
                        {
                            Id = 4,
                            Asin = "978-84-16588-43-5",
                            EditorialId = 2,
                            Paginas = 350,
                            Titulo = "Invisible"
                        },
                        new
                        {
                            Id = 5,
                            Asin = " 978-84-670-5330-2",
                            EditorialId = 3,
                            Paginas = 351,
                            Titulo = "Cómo hacer que te pasen cosas buenas"
                        },
                        new
                        {
                            Id = 6,
                            Asin = "978-84-670-6221-2",
                            EditorialId = 4,
                            Paginas = 641,
                            Titulo = "Encuentra tu persona vitamina"
                        },
                        new
                        {
                            Id = 7,
                            Asin = "978-84-204-6212-7",
                            EditorialId = 5,
                            Paginas = 852,
                            Titulo = "El caso Alaska Sanders"
                        },
                        new
                        {
                            Id = 8,
                            Asin = "978-84-01-02771-0",
                            EditorialId = 6,
                            Paginas = 963,
                            Titulo = "Cuento de hadas"
                        },
                        new
                        {
                            Id = 9,
                            Asin = "8457-96541574",
                            EditorialId = 7,
                            Paginas = 357,
                            Titulo = "Las hijas del Capitán"
                        });
                });

            modelBuilder.Entity("Libreria.Domain.LibroAutor", b =>
                {
                    b.Property<int>("LibroId")
                        .HasColumnType("int");

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("LibroId", "AutorId", "Id");

                    b.HasIndex("AutorId");

                    b.ToTable("LibroAutor");

                    b.HasData(
                        new
                        {
                            LibroId = 1,
                            AutorId = 1,
                            Id = 1
                        },
                        new
                        {
                            LibroId = 2,
                            AutorId = 2,
                            Id = 2
                        },
                        new
                        {
                            LibroId = 3,
                            AutorId = 3,
                            Id = 3
                        },
                        new
                        {
                            LibroId = 4,
                            AutorId = 4,
                            Id = 4
                        },
                        new
                        {
                            LibroId = 5,
                            AutorId = 5,
                            Id = 5
                        },
                        new
                        {
                            LibroId = 5,
                            AutorId = 5,
                            Id = 6
                        },
                        new
                        {
                            LibroId = 6,
                            AutorId = 1,
                            Id = 7
                        },
                        new
                        {
                            LibroId = 7,
                            AutorId = 2,
                            Id = 8
                        },
                        new
                        {
                            LibroId = 8,
                            AutorId = 3,
                            Id = 9
                        });
                });

            modelBuilder.Entity("Libreria.Domain.LibroGenero", b =>
                {
                    b.Property<int>("LibroId")
                        .HasColumnType("int");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("LibroId", "GeneroId", "Id");

                    b.HasIndex("GeneroId");

                    b.ToTable("LibroGenero");

                    b.HasData(
                        new
                        {
                            LibroId = 1,
                            GeneroId = 1,
                            Id = 1
                        },
                        new
                        {
                            LibroId = 1,
                            GeneroId = 2,
                            Id = 2
                        },
                        new
                        {
                            LibroId = 2,
                            GeneroId = 2,
                            Id = 3
                        },
                        new
                        {
                            LibroId = 3,
                            GeneroId = 3,
                            Id = 4
                        },
                        new
                        {
                            LibroId = 4,
                            GeneroId = 4,
                            Id = 5
                        },
                        new
                        {
                            LibroId = 4,
                            GeneroId = 5,
                            Id = 6
                        },
                        new
                        {
                            LibroId = 5,
                            GeneroId = 6,
                            Id = 7
                        },
                        new
                        {
                            LibroId = 6,
                            GeneroId = 7,
                            Id = 8
                        },
                        new
                        {
                            LibroId = 7,
                            GeneroId = 8,
                            Id = 9
                        },
                        new
                        {
                            LibroId = 8,
                            GeneroId = 3,
                            Id = 10
                        });
                });

            modelBuilder.Entity("Libreria.Domain.Precio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LibroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LibroId");

                    b.ToTable("Precio");
                });

            modelBuilder.Entity("Libreria.Domain.Libro", b =>
                {
                    b.HasOne("Libreria.Domain.Editorial", "Editorial")
                        .WithMany("Libros")
                        .HasForeignKey("EditorialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Editorial");
                });

            modelBuilder.Entity("Libreria.Domain.LibroAutor", b =>
                {
                    b.HasOne("Libreria.Domain.Autor", null)
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Libreria.Domain.Libro", null)
                        .WithMany()
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Libreria.Domain.LibroGenero", b =>
                {
                    b.HasOne("Libreria.Domain.Genero", null)
                        .WithMany()
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Libreria.Domain.Libro", null)
                        .WithMany()
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Libreria.Domain.Precio", b =>
                {
                    b.HasOne("Libreria.Domain.Libro", "Libro")
                        .WithMany("Precios")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("Libreria.Domain.Editorial", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("Libreria.Domain.Libro", b =>
                {
                    b.Navigation("Precios");
                });
#pragma warning restore 612, 618
        }
    }
}
